apiVersion: v1
kind: Service
metadata:
  name: mongoose-node
  labels:
    app: mongoose-node
  namespace: mongoose
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9999
    targetPort: 9999
  selector:
    name: mongoose-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongoose-node
  namespace: mongoose
spec:
  replicas: 4
  selector:
    matchLabels:
      name: mongoose-node
  serviceName: mongoose-node
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: mongoose-node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key:      "app"
                    operator: In
                    values:   ["mongoose-node"]
              topologyKey:    "kubernetes.io/hostname"
      containers:
        - image: emcmongoose/mongoose
          name: mongoose-node
          args: ["--run-node"]
          ports:
            - containerPort: 9999
