on: 
  push:
  workflow_call:
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      GPG_SECRET_KEY:
        required: true
      GPG_SECRET_KEY_PASSWORD:
        required: true
      GPG_SECRING:
        required: true
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2
      - name: Build JAR
        run: ./gradlew clean jar
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-jar
          path: build/libs/mongoose-*.jar
      - name: Check Tag
        id: check-tag
        run: |
             if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               echo "match=true" >> $GITHUB_OUTPUT
             fi
      # Release for tags matching the pattern "*.*.*"
      - name: Release to Maven
        if: steps.check-tag.outputs.match == 'true'
        run: |
             echo "${{ secrets.GPG_SECRING }}" | base64 -d > /tmp/secring.gpg
             ./gradlew -Psigning.keyId="${{ secrets.GPG_SECRET_KEY }}" -Psigning.password="${{ secrets.GPG_SECRET_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=/tmp/secring.gpg -PossrhUsername="${{ secrets.OSSRH_USERNAME }}" -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}" publishToNexus closeAndReleaseRepository
