on: 
  push:
  workflow_call:
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2
      - name: Build JAR
        run: ./gradlew clean jar
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-jar
          path: build/libs/mongoose-*.jar
      - name: Check Tag
        id: check-tag
        run: |
             if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               echo "match=true" >> $GITHUB_OUTPUT
             fi
      # Release for tags matching the pattern "*.*.*"
      - name: Release to Maven
        if: steps.check-tag.outputs.match == 'true'
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_SECRET_KEY_PASSWORD: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
          GPG_SECRING: ${{ secrets.GPG_SECRING }}
        run: |
             echo $GPG_SECRING | base64 -d > /tmp/secring.gpg
             ./gradlew -Psigning.keyId=${GPG_SECRET_KEY} -Psigning.password=${GPG_SECRET_KEY_PASSWORD} -Psigning.secretKeyRingFile=/tmp/secring.gpg -PossrhUsername=${OSSRH_USERNAME} -PossrhPassword=${OSSRH_PASSWORD} publishToNexus closeAndReleaseRepository
